### ISSUE TITLE
does  adabas-go-api  support concurrent Read queries against the Adabas TCP/IP port 60001

### ISSUE THREAD

**Issue by mckeederek** [SoftwareAG/adabas-go-api#2]
Using the store/softwareag/adabas-ce:6.7.0 docker image is it possible to execute concurrent Read queries against the Adabas TCP/IP port 60001?

**Comment by thknieling** [comment]
Sure it is possible to call multithreaded read queries. In the adabas-go-api each connection need to have to be created by adabas.NewConnection() to get separated TCP/IP connections and to separate UQ-IDS on the database.

**Comment by mckeederek** [comment]
Thank you for the quick response. I've encapsulated the Adabas Go client within a REST web service with each REST web service call instantiating a new connection via the adabas.NewConnection() method. The Adabas TCP/IP service seems to only process one query request at a time. When I attempt to execute 2 long running queries (via 2 concurrent REST web service requests) against the employee file  one succeeds and the other fails with a server communication error being returned to the Adabas Go client. Could this issue be related to the default Adabas database configuration in the store/softwareag/adabas-ce:6.7.0 docker image? If so, can you offer any advice on how best to configure the Adabas database to allow concurrent query requests?

**Comment by thknieling** [comment]
Each incoming REST server connection need to have a connection with an unique Adabas user id.
The automatic generated Adabas user Id in adabas-go-api should be unique.
Perhaps that does not work in your case.

The `testsuite` binary example starts a predefined parallel threads calling Adabas.
In the `main.go` file you can find a manual definition of user queue ids:

```
connStr := fmt.Sprintf("acj;target=%s;auth=NONE,id=%d,user=user%04d", c.url, c.threadNr, c.threadNr)
connection, err := adabas.NewConnection(connStr)
```

The `id` need to be unique. The `map` connection case is similar to the one with `target`.
The Adabas v6.7.0 has some issues because of CE edition limitations, but two connection should work in parallel, if I remember correctly.

**Comment by thknieling** [comment]
Closed after 20 days
